# Generated by Django 5.1 on 2024-08-12 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='counter',
            name='activities',
        ),
        migrations.AddField(
            model_name='activity',
            name='mode',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CounterActivityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.counter')),
            ],
            options={
                'unique_together': {('counter', 'activity', 'date')},
            },
        ),
    ]
