# Generated by Django 5.1 on 2024-08-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='code',
            field=models.PositiveIntegerField(default='0000', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='queuenumber',
            unique_together={('activity', 'number')},
        ),
    ]
