# Generated by Django 5.1 on 2024-08-13 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='current_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.activity'),
        ),
    ]
