# Generated by Django 5.1 on 2024-08-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_staffprofile_current_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuenumber',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.counter'),
        ),
    ]
