# Generated by Django 5.1 on 2024-08-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_queuenumber_unique_together_queuenumber_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuenumber',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
