# Generated by Django 5.1 on 2024-08-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_queuenumber_called_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuenumber',
            name='is_recalled',
            field=models.BooleanField(default=False),
        ),
    ]
